name: Create archive & release

on:
  push:
    tags:
      - '*' # triggers only if push new tag version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tar resources
        run: |
          tar -cf release.tar.gz /lib requirements.txt
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
